#!/system/bin/sh
_s=${EPOCHREALTIME:-0}
"/system/bin/ime" "$@"; _rc=$?
_e=${EPOCHREALTIME:-0}
printf '%s\t%s\time\t%s\t%s\n' "$_s" "$_e" "$_rc" "$*" >> "${CENSUS_LOG:-/data/local/tmp/census/fallback.log}" 2>/dev/null
exit $_rc
